### ISSUE TITLE
Notification to different rooms

### ISSUE THREAD

**Issue by szimszon** [opsdroid/skill-homeassistant#4]
Hi,

I'm wondering if could it be possible to send messages to different rooms?

```
+-------+                +------+      ---------
|       |--- to room1 ---|  OPS |------S Room1 S
| HA    |                |      |      ---------
|       |                |      |      ---------
|       |=== to room2 ===| DROID|======S Room2 S
+-------+                +------+      ---------

```

**Comment by jacobtomlinson** [comment]
This skill hasn't been maintained for a long time. You may want to check out [opsdroid-homeassistant](https://github.com/opsdroid/opsdroid-homeassistant) instead.

However to answer your specific question you could configure the skill multiple times with different names and room names, which would give you different endpoints to use in Home Assistant.
